### PR TITLE
code format symfony standard

### PR DESCRIPTION
**Pull request by pitrackster**
code reformat

### CODE REVIEW

**Comment by stefk** [comment]
:+1:

**Comment by stefk** [comment]
@pitrackster, I think generated code like migration files should be excluded.

**Comment by pitrackster** [comment]
@stefk  do you see other files/folder that should be ignored by the process ?

**Comment by stefk** [comment]
@pitrackster, no.

**Comment by pitrackster** [comment]
So we should exclude Migrations directory from the fixer.
It seems that the best way to do that is to create a .php_cs file in the root of the bundle and put something like below in it :

```
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->exclude('Migrations')
    ->in(__DIR__)
;

return Symfony\CS\Config\Config::create()
    ->finder($finder)
;
```

After that you can run the command with the --config-file parameter.

I'll revert the migration files to the previous state, add the config file and push again. It's ok for you ?

**Comment by stefk** [comment]
The config file is a good idea. While you're at it, you can also add php-cs-fixer to the dev dependencies ;)

**Pull request merged**
