### PR TITLE
Player refactoring

### PR DESCRIPTION
**Pull request by Elorfin**
Here is the refactoring for the Angular player which will permit to integrate the templates (all components of a Question are now highly decoupled to be able to move them where we want in the UI).

It also includes some bug fixes (discussed in meetings and referenced in the commit messages).

From my tests, I have already found some bugs, but I will not have any time to fix them before I take my vacation. So I have opened issues about them : 
- claroline/Distribution#149
- claroline/Distribution#150
- claroline/Distribution#151
- claroline/Distribution#152
- claroline/Distribution#153

@Cindy42 : I have moved the Timer into a stand alone directive, I think someday we will want to use it elsewhere (maybe in PathBundle ?)

There certainly are other problems but I have not yet encountered them and I have no more time.

Anyway it's OK for me to merge the bundle in the Distribution @LaurentGruber @stefk @ngodfraind.

### CODE REVIEW

**Comment by Elorfin** [comment]
I have forgotten 2 points : 
- Score is now retrieve from the API for the formative questions. It needs to be added to the Corrections too (~1/2 day).
- Solutions are never exported unless they are requested (second parameter of ExerciseManager::exportExercise() set to true). For the immediate feedback the API exposed the solutions in all case, which was a security breach.

**Comment by stefk** [comment]
When this is merged, if everybody is ready to move v6 development to the distribution, we can open a PR for that. It might take a little time to integrate the bundle but at least there would be a dedicated branch to work with and developement could go on in the meantime.

@david42, @charlotte42, @marion42, @Elorfin, @pitrackster, @eldoniel, @ngodfraind.

**Comment by Elorfin** [comment]
It's OK for me. Anyway, I don't we can considerate my work as stable for now (I rushed this last days to make this pull-request and it needs more tests).

@stefk : have you seen the build have failed ? It seems there is a problem in travis at the Claroline installation. I'm not familiar with this part of the app and I can't figure out why it failed.

**Comment by david42** [comment]
I can create a PR to merge in the master.
The next week we will be on vacation and I think the Grenoble team also.
If this is the case, it it's not necessary create a new branch ?

**Comment by stefk** [comment]
@Elorfin, the build error is due to an update of the internal API of composer (we use it programmatically in some places). This is fixed in claroline/Distribution. If there are other build errors for this bundle, they will be caught in the import PR.

@david42, if I remember correctly, we said `v6` was the branch to merge into claroline/Distribution. Doing a merge `v6 -> master` or creating another branch isn't necessary IMO. The only condition is that there's no major development not merged into `v6` yet.

**Comment by david42** [comment]
@stefk I remember that we will use the master branch for the distribution. Now master and V6 are indentically, so we use one or the other.

**Comment by stefk** [comment]
@david42, ok, we'll take the master then. The import process will start next week. Can we say that v6 development is frozen here?

**Comment by Elorfin** [comment]
ping @eldoniel.

**Comment by david42** [comment]
@stefk Next week there will be no development UJM.  Then, we will use "Distribution".

**Comment by eldoniel** [comment]
@stefk I might go back to work on the remaining match question feedback during the next week, but there's no hurry. Do you know about what moment of the week you will do the import, so that I know if I can start before or wait until it's done?

**Comment by stefk** [comment]
@eldoniel, see https://github.com/claroline/Distribution/pull/156#issuecomment-211242441.

**Pull request merged**
